name: common_dart
description: "公共 Dart 工具库"
version: 1.0.1
homepage: https://github.com/jiangwenfan/common_flutter
repository: https://github.com/jiangwenfan/common_flutter
issue_tracker: https://github.com/jiangwenfan/common_flutter/issues

environment:
  sdk: ^3.9.2

# Add regular dependencies here.
dependencies:
  dio: ^5.4.0
  crypto: ^3.0.7
  logger: ^2.6.2

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
  dotenv: ^4.2.0
