name: common_dart
description: A starting point for Dart libraries or applications.
version: 1.0.0
homepage: https://github.com/jiangwenfan/common_flutter
repository: https://github.com/jiangwenfan/common_flutter
issue_tracker: https://github.com/jiangwenfan/common_flutter/issues

environment:
  sdk: ^3.9.2

# Add regular dependencies here.
dependencies:
  # path: ^1.9.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
